version: '3'
services:
  web: 
    build:
      context: . # Dove trovare tutti i file necessari per il progetto
      dockerfile: Dockerfile.dev 
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "2000:1000"
    volumes:
      - /app/node_modules 
      - .:/app 
    command: ["npm", "run", "test"]